name: Code CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build code
        run: pnpm build

      - name: Test
        run: pnpm test
